name: Anodyne C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download and extract GBDK
      run: |
        cd ..
        wget https://github.com/gbdk-2020/gbdk-2020/releases/download/4.5.0/gbdk-linux64.tar.gz
        tar -xzf gbdk-linux64.tar.gz

    - name: Build code
      run: |
        cd src
        mkdir build
        cd build
        cmake ..
        make -j2
        cd ..
        make
